import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Carpet Cleaning Melbourne | Professional Carpet Cleaners | From $35/room',
  description: 'Professional carpet cleaning services in Melbourne. Deep steam cleaning, stain & odor removal, rug, sofa, and mattress cleaning. Eco-friendly | same day service | 100% satisfaction guarantee. Book your carpet clean today!',
  keywords: 'carpet cleaning melbourne, professional carpet cleaners, carpet stain removal, deep carpet cleaning, eco friendly carpet cleaning, carpet sanitization, rug cleaning, sofa cleaning, mattress cleaning, upholstery cleaning, commercial carpet cleaning, residential carpet cleaning, steam cleaning, pet stain removal, same day carpet cleaning, carpet cleaning company melbourne',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'Carpet Cleaning Melbourne | Professional Carpet Cleaners',
    description: 'Expert carpet cleaning in Melbourne. Deep steam cleaning, stain & odor removal, rug, sofa, and mattress cleaning. Eco-friendly, same day service, 100% satisfaction guarantee.',
    url: 'https://www.cleaningprofessionals.com.au/services/carpet-cleaning/',
    siteName: 'Cleaning Professionals Melbourne',
    images: [
      {
        url: '/images/carpet-cleaning-melbourne.jpg',
        width: 1200,
        height: 630,
        alt: 'Professional Carpet Cleaning Services Melbourne',
      },
    ],
    locale: 'en_AU',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Carpet Cleaning Melbourne | Book Today',
    description: 'Professional carpet cleaning in Melbourne. Deep steam cleaning, stain & odor removal, rug, sofa, and mattress cleaning. Eco-friendly, same day service.',
    images: ['/images/carpet-cleaning-melbourne.jpg'],
  },
  alternates: {
    canonical: '/services/carpet-cleaning/',
  },
  authors: [{ name: 'Cleaning Professionals Melbourne' }],
  generator: 'Next.js',
  applicationName: 'Carpet Cleaning Services Melbourne',
  referrer: 'origin-when-cross-origin',
  creator: 'Cleaning Professionals Melbourne',
  publisher: 'Cleaning Professionals Melbourne',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
  verification: {
    google: 'G-W87SXGYKC1',
  },
  category: 'Carpet Cleaning Services',
  other: {
    'geo.region': 'AU-VIC',
    'geo.placename': 'Melbourne',
    'geo.position': '-37.8136;144.9631',
    'ICBM': '-37.8136, 144.9631',
    'og:price:amount': '35.00',
    'og:price:currency': 'AUD',
    'business:contact_data:locality': 'Melbourne',
    'business:contact_data:region': 'Victoria',
    'business:contact_data:country': 'Australia',
    'og:availability': 'in stock',
    'business:hours:day': 'Mon-Sun 7:00-20:00',
    'og:service:type': 'Carpet Cleaning',
    'og:phone_number': '0450124086',
    'og:service:features': 'Deep steam cleaning, stain removal, rug cleaning, sofa cleaning, mattress cleaning, eco-friendly, pet stain removal, same day service, 100% satisfaction guarantee',
    'og:service:area': 'Melbourne, Victoria, Australia',
    'og:service:category': 'Residential & Commercial Carpet Cleaning',
    'og:service:booking_url': 'https://www.cleaningprofessionals.com.au/services/carpet-cleaning/book',
    'og:service:rating': '4.9',
    'og:service:review_count': '2500',
    'og:service:provider': 'Cleaning Professionals Melbourne',
  }
} 